"""Generate the README case study: real numbers, real charts, one honest story.

Runs the full evaluation stack on SPY 2015–2025 (fixed window so the numbers
in the README are reproducible), writes chart PNGs to assets/, and emits
assets/case_study.md with every table the README embeds.

Run from the repo root:  python scripts/run_case_study.py
Requires the dev extras:  pip install -r requirements-dev.txt
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

import pandas as pd
import plotly.graph_objects as go

from src.data import fetch_prices
from src.engine import run_backtest, run_naive_backtest_do_not_use
from src.evaluate import evaluate_strategy, format_metric, plot_drawdown, plot_equity_curve
from src.ensemble import ensemble_backtest, strategy_correlations
from src.evaluate import split_in_out_sample
from src.metrics import alpha_beta, information_ratio, sharpe_ratio
from src.regimes import regime_performance, vix_regimes
from src.robustness import cross_asset_check, robustness_summary
from src.sizing import volatility_target
from src.stats import block_bootstrap_sharpe, expected_max_sharpe
from src.strategies import STRATEGY_REGISTRY
from src.style import BENCHMARK_COLOR, NEGATIVE_COLOR, STRATEGY_COLOR, base_layout
from src.sweep import best_in_sample, oos_rank_of_is_best, parameter_sweep, sweep_heatmap_pair
from src.walkforward import plot_walk_forward, walk_forward

TICKER, START, END = "SPY", "2015-01-01", "2025-01-01"
TRAIN_FRAC, COST_BPS = 0.7, 5.0
ASSETS = REPO / "assets"

MA_SWEEP_GRID = {"fast": [5, 10, 15, 20, 30, 40, 50, 60],
                 "slow": [30, 50, 75, 100, 125, 150, 200, 250]}
MA_WF_GRID = {"fast": [10, 20, 50], "slow": [50, 100, 200]}

ROW_METRICS = ["CAGR", "Sharpe", "Sortino", "Max drawdown", "Win rate (daily)", "Exposure"]


def png(fig: go.Figure, name: str, width=1100, height=460) -> None:
    fig.write_image(ASSETS / name, width=width, height=height, scale=2)
    print(f"  chart → assets/{name}")


def metrics_row(name: str, seg: dict) -> str:
    cells = " | ".join(format_metric(m, seg.get(m)) for m in ROW_METRICS)
    return f"| {name} | {cells} |"


def main() -> None:
    ASSETS.mkdir(exist_ok=True)
    prices = fetch_prices(TICKER, START, END)
    assert prices is not None, "data fetch failed"
    print(f"{TICKER}: {len(prices)} bars {prices.index[0].date()} → {prices.index[-1].date()}")

    lines: list[str] = []
    lines.append(f"<!-- generated by scripts/run_case_study.py — {TICKER} {START}→{END}, "
                 f"{TRAIN_FRAC:.0%} in-sample, {COST_BPS:.0f} bps costs -->\n")

    # ── 1. Three strategies, in-sample vs out-of-sample ────────────────────
    results = {}
    for name in STRATEGY_REGISTRY:
        results[name] = evaluate_strategy(name, prices, train_frac=TRAIN_FRAC, cost_bps=COST_BPS)
        print(f"  {name}: {results[name].verdict[:100]}")

    bench = next(iter(results.values()))
    split = bench.split_date.date()
    header = "| | " + " | ".join(ROW_METRICS) + " |"
    sep = "|---" * (len(ROW_METRICS) + 1) + "|"

    lines.append(f"### In-sample ({prices.index[0].date()} → {split}, where parameters could have been tuned)\n")
    lines += [header, sep]
    for name, r in results.items():
        lines.append(metrics_row(name, r.in_sample))
    lines.append(metrics_row("**Buy & hold**", bench.benchmark_in_sample))

    lines.append(f"\n### Out-of-sample ({split} → {prices.index[-1].date()}, untouched during tuning)\n")
    lines += [header, sep]
    for name, r in results.items():
        lines.append(metrics_row(name, r.out_of_sample))
    lines.append(metrics_row("**Buy & hold**", bench.benchmark_out_of_sample))

    lines.append("\n### The verdict line each run prints\n")
    for name, r in results.items():
        lines.append(f"- **{name}** — {r.verdict}")

    # ── 1b. CAPM: what does the market explain? (out-of-sample) ────────────
    lines.append("\n### Out-of-sample CAPM regression vs SPY\n")
    lines.append("| Strategy | Beta | Alpha (ann.) | R² | Information ratio |")
    lines.append("|---|---|---|---|---|")
    for name, r in results.items():
        oos_mask = r.results.index >= r.split_date
        rs = r.results.loc[oos_mask, "daily_return"]
        rb = r.benchmark.loc[oos_mask, "daily_return"]
        capm = alpha_beta(rs, rb)
        ir = information_ratio(rs, rb)
        lines.append(
            f"| {name} | {capm['beta']:.2f} | {capm['alpha_ann']:+.1%} "
            f"| {capm['r2']:.2f} | {ir:.2f} |"
        )

    # ── 1c. Volatility targeting: same signal, risk-managed size ───────────
    def vt_hold(prices_, **_):
        return volatility_target(pd.Series(1.0, index=prices_.index), prices_, target_vol=0.10)

    vt = evaluate_strategy(vt_hold, prices, train_frac=TRAIN_FRAC, cost_bps=COST_BPS)
    bh_oos, vt_oos = vt.benchmark_out_of_sample, vt.out_of_sample
    lines.append(
        "\n### Volatility targeting (10% target) applied to buy-and-hold, out-of-sample\n\n"
        "| | Volatility (ann.) | Sharpe | Max drawdown | CAGR |\n|---|---|---|---|---|\n"
        f"| Buy & hold | {bh_oos['Volatility (ann.)']:.1%} | {bh_oos['Sharpe']:.2f} "
        f"| {bh_oos['Max drawdown']:.1%} | {format_metric('CAGR', bh_oos['CAGR'])} |\n"
        f"| Vol-targeted buy & hold | {vt_oos['Volatility (ann.)']:.1%} | {vt_oos['Sharpe']:.2f} "
        f"| {vt_oos['Max drawdown']:.1%} | {format_metric('CAGR', vt_oos['CAGR'])} |\n"
    )

    # ── 1d. VIX regime attribution: where the money was made and lost ──────
    regimes = vix_regimes(prices)
    if regimes is not None:
        ma = results["MA Crossover"]
        table = regime_performance(
            {"MA Crossover": ma.results["daily_return"], "Buy & hold": ma.benchmark["daily_return"]},
            regimes,
        )
        lines.append("\n### Performance by VIX regime (full period, MA Crossover 20/50)\n")
        lines.append("| Regime | Days | MA ann. return | MA Sharpe | B&H ann. return | B&H Sharpe |")
        lines.append("|---|---|---|---|---|---|")
        for regime, row in table.iterrows():
            def _f(v, pct=False):
                if pd.isna(v):
                    return "—"
                return f"{v:+.1%}" if pct else f"{v:.2f}"
            lines.append(
                f"| {regime} | {int(row['Days'])} "
                f"| {_f(row['MA Crossover · ann. return'], pct=True)} | {_f(row['MA Crossover · Sharpe'])} "
                f"| {_f(row['Buy & hold · ann. return'], pct=True)} | {_f(row['Buy & hold · Sharpe'])} |"
            )
        lines.append(
            "\n(Regimes by the day's VIX close: calm < 15, stressed > 25 — fixed thresholds, "
            "no look-ahead. Diagnostic only; the engine never sees the labels.)"
        )

    # ── 2. Bootstrap: is the OOS Sharpe distinguishable from zero? ─────────
    lines.append("\n### Bootstrap reality check (out-of-sample Sharpe, 95% CI)\n")
    lines.append("| Strategy | OOS Sharpe | 95% CI | P(Sharpe ≤ 0) |")
    lines.append("|---|---|---|---|")
    for name, r in results.items():
        oos = r.results.loc[r.results.index >= r.split_date, "daily_return"]
        b = block_bootstrap_sharpe(oos, n_boot=2000, seed=7)
        lines.append(f"| {name} | {b.point:.2f} | [{b.lo:.2f}, {b.hi:.2f}] | {b.p_leq_zero:.0%} |")

    # ── 3. Charts for the headline strategy (MA Crossover) ─────────────────
    ma = results["MA Crossover"]
    png(plot_equity_curve(ma), "equity_ma_crossover.png")
    png(plot_drawdown(ma), "drawdown_ma_crossover.png")

    # ── 4. The look-ahead lie, drawn ────────────────────────────────────────
    rets = prices["Close"].pct_change().fillna(0.0)
    peeking = (rets > 0).astype(float)
    naive = run_naive_backtest_do_not_use(prices, peeking)
    honest = run_backtest(prices, peeking, cost_bps=COST_BPS)
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=naive.index, y=naive["equity"], name="Naive engine (peeks, trades free)",
                             line=dict(color=NEGATIVE_COLOR, width=2)))
    fig.add_trace(go.Scatter(x=honest.index, y=honest["equity"], name="Honest engine (shifted, 5 bps)",
                             line=dict(color=STRATEGY_COLOR, width=2)))
    fig.add_trace(go.Scatter(x=prices.index, y=100_000 * prices["Close"] / prices["Close"].iloc[0],
                             name="Buy & hold", line=dict(color=BENCHMARK_COLOR, width=1.5, dash="dash")))
    fig.update_layout(**base_layout('"Buy on up days" — the same rule through two engines',
                                    y_title="Equity ($, log)"))
    fig.update_yaxes(type="log")
    png(fig, "lookahead_lie.png")
    lines.append(
        f"\nThe peeking rule ends the decade at **${naive['equity'].iloc[-1]:,.0f}** in the naive "
        f"engine and **${honest['equity'].iloc[-1]:,.0f}** in the honest one "
        f"(buy-and-hold: ${100_000 * prices['Close'].iloc[-1] / prices['Close'].iloc[0]:,.0f})."
    )

    # ── 5. Parameter sweep: overfitting as a picture ───────────────────────
    sweep_df = parameter_sweep("MA Crossover", prices, MA_SWEEP_GRID,
                               train_frac=TRAIN_FRAC, cost_bps=COST_BPS)
    png(sweep_heatmap_pair(sweep_df, x="fast", y="slow"), "sweep_ma_crossover.png", height=470)
    best = best_in_sample(sweep_df)
    rank, pct = oos_rank_of_is_best(sweep_df)
    n_is_obs = int((prices.index < bench.split_date).sum())
    luck = expected_max_sharpe(len(sweep_df), n_is_obs)
    lines.append(
        f"\n### Parameter sweep ({len(sweep_df)} MA-crossover combos)\n\n"
        f"The in-sample champion (fast={best['fast']:.0f}, slow={best['slow']:.0f}) posts an "
        f"in-sample Sharpe of **{best['is_sharpe']:.2f}** — and ranks **#{rank} of "
        f"{len(sweep_df)}** out-of-sample (Sharpe {best['oos_sharpe']:.2f}, beating just "
        f"{pct:.0%} of the very grid it champions).\n\n"
        f"**Luck yardstick:** the expected best in-sample Sharpe from {len(sweep_df)} "
        f"*zero-skill* combos on this window is **≈{luck:.2f}** (expected-maximum-Sharpe "
        f"under the null). The champion's {best['is_sharpe']:.2f} barely clears the bar "
        f"that pure sampling error sets."
    )

    # ── 6. Walk-forward: the reality gap ────────────────────────────────────
    wf = walk_forward("MA Crossover", prices, MA_WF_GRID, n_windows=5, cost_bps=COST_BPS)
    bench_eq = 100_000 * (1 + rets.loc[wf.oos_returns.index]).cumprod()
    png(plot_walk_forward(wf, benchmark_equity=bench_eq), "walkforward_ma_crossover.png")
    lines.append(
        f"\n### Walk-forward (5 windows, re-optimized each time)\n\n"
        f"| | Sharpe |\n|---|---|\n"
        f"| Hindsight-optimized, full sample ({', '.join(f'{k}={v}' for k, v in wf.hindsight_params.items())}) "
        f"| {wf.hindsight_sharpe:.2f} |\n"
        f"| **Walk-forward, all out-of-sample** | **{wf.oos_metrics['Sharpe']:.2f}** |\n"
        f"| Buy & hold, same window | {wf.benchmark_metrics['Sharpe']:.2f} |\n"
    )
    lines.append("Chosen parameters per window: " +
                 "; ".join(", ".join(f"{k}={v}" for k, v in w.best_params.items()) for w in wf.windows) + ".")

    # ── 6b. Does the edge travel? Cross-asset + ensemble ───────────────────
    basket = cross_asset_check("MA Crossover", start=START, end=END,
                               train_frac=TRAIN_FRAC, cost_bps=COST_BPS, fast=20, slow=50)
    testable = basket[basket["bars"] > 0].dropna(subset=["oos_sharpe"])
    s = robustness_summary(basket)
    lines.append("\n### Does the edge travel? (MA 20/50 across a liquid-ETF basket, out-of-sample)\n")
    lines.append("| Ticker | OOS Sharpe (strategy) | OOS Sharpe (buy & hold) | Edge |")
    lines.append("|---|---|---|---|")
    for _, row in testable.iterrows():
        lines.append(f"| {row['ticker']} | {row['oos_sharpe']:.2f} | {row['bh_oos_sharpe']:.2f} "
                     f"| {row['oos_edge']:+.2f} |")
    lines.append(
        f"\nAcross {s['tickers_tested']} tickers the strategy beat buy-and-hold on "
        f"**{s['beat_benchmark_frac']:.0%}** of them (median OOS Sharpe "
        f"{s['median_oos_sharpe']:.2f})."
    )

    ens, indiv = ensemble_backtest(prices, cost_bps=COST_BPS)
    split_date = split_in_out_sample(prices, TRAIN_FRAC)
    corr = strategy_correlations(indiv)
    lines.append("\n### Diversifying across strategies (SPY, out-of-sample Sharpe)\n")
    lines.append("| | OOS Sharpe |\n|---|---|")
    for name, res in {**indiv, "**Equal-weight ensemble**": ens}.items():
        oos = res.loc[res.index >= split_date, "daily_return"]
        lines.append(f"| {name} | {sharpe_ratio(oos):.2f} |")
    pairs = [f"{a}↔{b}: {corr.loc[a, b]:.2f}"
             for i, a in enumerate(corr.index) for b in corr.columns[i + 1:]]
    lines.append(f"\nActive-day return correlations — {'; '.join(pairs)}.")

    # ── 7. Cost sensitivity ─────────────────────────────────────────────────
    lines.append("\n### What realistic costs do (MA Crossover 20/50, out-of-sample)\n")
    lines.append("| Cost per trade | OOS CAGR | OOS Sharpe |")
    lines.append("|---|---|---|")
    for bps in (0, 5, 10, 25):
        r = evaluate_strategy("MA Crossover", prices, train_frac=TRAIN_FRAC, cost_bps=bps)
        lines.append(f"| {bps} bps | {format_metric('CAGR', r.out_of_sample['CAGR'])} "
                     f"| {format_metric('Sharpe', r.out_of_sample['Sharpe'])} |")

    out = ASSETS / "case_study.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"\ncase study fragment → {out.relative_to(REPO)}")


if __name__ == "__main__":
    main()
