"""Generate the README case study: real numbers, real charts, one honest story.

Runs the full evaluation stack on SPY 2015–2025 (fixed window so the numbers
in the README are reproducible), writes chart PNGs to assets/, and emits
assets/case_study.md with every table the README embeds.

Run from the repo root:  python scripts/run_case_study.py
Requires the dev extras:  pip install -r requirements-dev.txt
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

import pandas as pd
import plotly.graph_objects as go

from src.data import fetch_prices
from src.engine import run_backtest, run_naive_backtest_do_not_use
from src.evaluate import evaluate_strategy, format_metric, plot_drawdown, plot_equity_curve
from src.stats import block_bootstrap_sharpe
from src.strategies import STRATEGY_REGISTRY
from src.style import BENCHMARK_COLOR, NEGATIVE_COLOR, STRATEGY_COLOR, base_layout
from src.sweep import best_in_sample, oos_rank_of_is_best, parameter_sweep, sweep_heatmap_pair
from src.walkforward import plot_walk_forward, walk_forward

TICKER, START, END = "SPY", "2015-01-01", "2025-01-01"
TRAIN_FRAC, COST_BPS = 0.7, 5.0
ASSETS = REPO / "assets"

MA_SWEEP_GRID = {"fast": [5, 10, 15, 20, 30, 40, 50, 60],
                 "slow": [30, 50, 75, 100, 125, 150, 200, 250]}
MA_WF_GRID = {"fast": [10, 20, 50], "slow": [50, 100, 200]}

ROW_METRICS = ["CAGR", "Sharpe", "Sortino", "Max drawdown", "Win rate (daily)", "Exposure"]


def png(fig: go.Figure, name: str, width=1100, height=460) -> None:
    fig.write_image(ASSETS / name, width=width, height=height, scale=2)
    print(f"  chart → assets/{name}")


def metrics_row(name: str, seg: dict) -> str:
    cells = " | ".join(format_metric(m, seg.get(m)) for m in ROW_METRICS)
    return f"| {name} | {cells} |"


def main() -> None:
    ASSETS.mkdir(exist_ok=True)
    prices = fetch_prices(TICKER, START, END)
    assert prices is not None, "data fetch failed"
    print(f"{TICKER}: {len(prices)} bars {prices.index[0].date()} → {prices.index[-1].date()}")

    lines: list[str] = []
    lines.append(f"<!-- generated by scripts/run_case_study.py — {TICKER} {START}→{END}, "
                 f"{TRAIN_FRAC:.0%} in-sample, {COST_BPS:.0f} bps costs -->\n")

    # ── 1. Three strategies, in-sample vs out-of-sample ────────────────────
    results = {}
    for name in STRATEGY_REGISTRY:
        results[name] = evaluate_strategy(name, prices, train_frac=TRAIN_FRAC, cost_bps=COST_BPS)
        print(f"  {name}: {results[name].verdict[:100]}")

    bench = next(iter(results.values()))
    split = bench.split_date.date()
    header = "| | " + " | ".join(ROW_METRICS) + " |"
    sep = "|---" * (len(ROW_METRICS) + 1) + "|"

    lines.append(f"### In-sample ({prices.index[0].date()} → {split}, where parameters could have been tuned)\n")
    lines += [header, sep]
    for name, r in results.items():
        lines.append(metrics_row(name, r.in_sample))
    lines.append(metrics_row("**Buy & hold**", bench.benchmark_in_sample))

    lines.append(f"\n### Out-of-sample ({split} → {prices.index[-1].date()}, untouched during tuning)\n")
    lines += [header, sep]
    for name, r in results.items():
        lines.append(metrics_row(name, r.out_of_sample))
    lines.append(metrics_row("**Buy & hold**", bench.benchmark_out_of_sample))

    lines.append("\n### The verdict line each run prints\n")
    for name, r in results.items():
        lines.append(f"- **{name}** — {r.verdict}")

    # ── 2. Bootstrap: is the OOS Sharpe distinguishable from zero? ─────────
    lines.append("\n### Bootstrap reality check (out-of-sample Sharpe, 95% CI)\n")
    lines.append("| Strategy | OOS Sharpe | 95% CI | P(Sharpe ≤ 0) |")
    lines.append("|---|---|---|---|")
    for name, r in results.items():
        oos = r.results.loc[r.results.index >= r.split_date, "daily_return"]
        b = block_bootstrap_sharpe(oos, n_boot=2000, seed=7)
        lines.append(f"| {name} | {b.point:.2f} | [{b.lo:.2f}, {b.hi:.2f}] | {b.p_leq_zero:.0%} |")

    # ── 3. Charts for the headline strategy (MA Crossover) ─────────────────
    ma = results["MA Crossover"]
    png(plot_equity_curve(ma), "equity_ma_crossover.png")
    png(plot_drawdown(ma), "drawdown_ma_crossover.png")

    # ── 4. The look-ahead lie, drawn ────────────────────────────────────────
    rets = prices["Close"].pct_change().fillna(0.0)
    peeking = (rets > 0).astype(float)
    naive = run_naive_backtest_do_not_use(prices, peeking)
    honest = run_backtest(prices, peeking, cost_bps=COST_BPS)
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=naive.index, y=naive["equity"], name="Naive engine (peeks, trades free)",
                             line=dict(color=NEGATIVE_COLOR, width=2)))
    fig.add_trace(go.Scatter(x=honest.index, y=honest["equity"], name="Honest engine (shifted, 5 bps)",
                             line=dict(color=STRATEGY_COLOR, width=2)))
    fig.add_trace(go.Scatter(x=prices.index, y=100_000 * prices["Close"] / prices["Close"].iloc[0],
                             name="Buy & hold", line=dict(color=BENCHMARK_COLOR, width=1.5, dash="dash")))
    fig.update_layout(**base_layout('"Buy on up days" — the same rule through two engines',
                                    y_title="Equity ($, log)"))
    fig.update_yaxes(type="log")
    png(fig, "lookahead_lie.png")
    lines.append(
        f"\nThe peeking rule ends the decade at **${naive['equity'].iloc[-1]:,.0f}** in the naive "
        f"engine and **${honest['equity'].iloc[-1]:,.0f}** in the honest one "
        f"(buy-and-hold: ${100_000 * prices['Close'].iloc[-1] / prices['Close'].iloc[0]:,.0f})."
    )

    # ── 5. Parameter sweep: overfitting as a picture ───────────────────────
    sweep_df = parameter_sweep("MA Crossover", prices, MA_SWEEP_GRID,
                               train_frac=TRAIN_FRAC, cost_bps=COST_BPS)
    png(sweep_heatmap_pair(sweep_df, x="fast", y="slow"), "sweep_ma_crossover.png", height=470)
    best = best_in_sample(sweep_df)
    rank, pct = oos_rank_of_is_best(sweep_df)
    lines.append(
        f"\n### Parameter sweep ({len(sweep_df)} MA-crossover combos)\n\n"
        f"The in-sample champion (fast={best['fast']:.0f}, slow={best['slow']:.0f}) posts an "
        f"in-sample Sharpe of **{best['is_sharpe']:.2f}** — and ranks **#{rank} of "
        f"{len(sweep_df)}** out-of-sample (Sharpe {best['oos_sharpe']:.2f}, beating just "
        f"{pct:.0%} of the very grid it champions)."
    )

    # ── 6. Walk-forward: the reality gap ────────────────────────────────────
    wf = walk_forward("MA Crossover", prices, MA_WF_GRID, n_windows=5, cost_bps=COST_BPS)
    bench_eq = 100_000 * (1 + rets.loc[wf.oos_returns.index]).cumprod()
    png(plot_walk_forward(wf, benchmark_equity=bench_eq), "walkforward_ma_crossover.png")
    lines.append(
        f"\n### Walk-forward (5 windows, re-optimized each time)\n\n"
        f"| | Sharpe |\n|---|---|\n"
        f"| Hindsight-optimized, full sample ({', '.join(f'{k}={v}' for k, v in wf.hindsight_params.items())}) "
        f"| {wf.hindsight_sharpe:.2f} |\n"
        f"| **Walk-forward, all out-of-sample** | **{wf.oos_metrics['Sharpe']:.2f}** |\n"
        f"| Buy & hold, same window | {wf.benchmark_metrics['Sharpe']:.2f} |\n"
    )
    lines.append("Chosen parameters per window: " +
                 "; ".join(", ".join(f"{k}={v}" for k, v in w.best_params.items()) for w in wf.windows) + ".")

    # ── 7. Cost sensitivity ─────────────────────────────────────────────────
    lines.append("\n### What realistic costs do (MA Crossover 20/50, out-of-sample)\n")
    lines.append("| Cost per trade | OOS CAGR | OOS Sharpe |")
    lines.append("|---|---|---|")
    for bps in (0, 5, 10, 25):
        r = evaluate_strategy("MA Crossover", prices, train_frac=TRAIN_FRAC, cost_bps=bps)
        lines.append(f"| {bps} bps | {format_metric('CAGR', r.out_of_sample['CAGR'])} "
                     f"| {format_metric('Sharpe', r.out_of_sample['Sharpe'])} |")

    out = ASSETS / "case_study.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"\ncase study fragment → {out.relative_to(REPO)}")


if __name__ == "__main__":
    main()
